server:
  port: 8000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: consumer
          uri: lb://consumer-server
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1

        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true



logging:
  level:
    com.zan: error
